---
## Site settings
title: Peter Hoffmann
description: >-
  flyinggreenfrog
knowledgebase-categories:
  - Container
  - Linux
  - Network
  - Programming
  - Security
  - Systemsmanagement
  - Technologies
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "en"

## Build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: True
  hard_wrap: False
  syntax_highlighter: rouge
