## Site settings
title: Peter Hoffmann
description: >-
  flyinggreenfrog
knowledgebase-categories: [Linux, Network, Programming, Security, Systemsmanagement, Technologies]
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "en"

## Build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
