---
site:
  title: Flyinggreenfrog
  url: https://flyinggreenfrog.github.io
content:
  sources:
    - url: https://github.com/flyinggreenfrog/flyinggreenfrog.github.io.git
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
          - .nojekyll
          - gpg/0x295DD887892FF56B.pub.gpg
          - gpg/0x295DD887892FF56B.pub.asc
          - gpg/0x4EFF1B9A87D6DBB0.pub.gpg
          - gpg/0x4EFF1B9A87D6DBB0.pub.asc
          - gpg/0x909B4900403C82BE.pub.gpg
          - gpg/0x909B4900403C82BE.pub.asc
    - path: .nojekyll
    - path: gpg/0x295DD887892FF56B.pub.gpg
      contents: ./supplemental-ui/gpg/0x295DD887892FF56B.pub.gpg
    - path: gpg/0x295DD887892FF56B.pub.asc
      contents: ./supplemental-ui/gpg/0x295DD887892FF56B.pub.asc
    - path: gpg/0x4EFF1B9A87D6DBB0.pub.gpg
      contents: ./supplemental-ui/gpg/0x4EFF1B9A87D6DBB0.pub.gpg
    - path: gpg/0x4EFF1B9A87D6DBB0.pub.asc
      contents: ./supplemental-ui/gpg/0x4EFF1B9A87D6DBB0.pub.asc
    - path: gpg/0x909B4900403C82BE.pub.gpg
      contents: ./supplemental-ui/gpg/0x909B4900403C82BE.pub.gpg
    - path: gpg/0x909B4900403C82BE.pub.asc
      contents: ./supplemental-ui/gpg/0x909B4900403C82BE.pub.asc
    - path: partials/header-content.hbs
      contents: ./supplemental-ui/partials/header-content.hbs
    - path: partials/nav.hbs
      contents: |
        <div class="nav-container"{{#if page.component}} data-component="{{page.component.name}}" data-version="{{page.version}}"{{/if}}>
          <aside class="nav">
            <div class="panels">
        {{> nav-menu}}
            </div>
          </aside>
        </div>
    - path: partials/footer-content.hbs
      contents: |
        <footer class="footer">
          <p>Copyright (C) <a href="https://github.com/flyinggreenfrog">flyinggreenfrog</a></p>
        </footer>
asciidoc:
  attributes:
    experimental: ''
