---
site:
  title: Flyinggreenfrog
  url: https://flyinggreenfrog.github.io
  start_page: flyinggreenfrog::index.adoc
content:
  sources:
    - url: https://github.com/flyinggreenfrog/flyinggreenfrog.github.io.git
      start_path: flyinggreenfrog
    - url: https://github.com/flyinggreenfrog/flyinggreenfrog.github.io.git
      start_path: knowledgebase
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
          - .nojekyll
    - path: .nojekyll
    - path: partials/header-content.hbs
      contents: ./supplemental-ui/partials/header-content.hbs
    - path: partials/footer-content.hbs
      contents: |
        <footer class="footer">
          <p>Copyright (C) <a href="https://github.com/flyinggreenfrog">flyinggreenfrog</a></p>
        </footer>
asciidoc:
  attributes:
    experimental: ''
